//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace copy_image {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("copy_image.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 add failed! 的本地化字符串。
        /// </summary>
        internal static string t_AddFail {
            get {
                return ResourceManager.GetString("AddFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 added successfully. 的本地化字符串。
        /// </summary>
        internal static string t_AddOK {
            get {
                return ResourceManager.GetString("AddOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Compressed 的本地化字符串。
        /// </summary>
        internal static string t_Compressed {
            get {
                return ResourceManager.GetString("Compressed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copied 的本地化字符串。
        /// </summary>
        internal static string t_Copied {
            get {
                return ResourceManager.GetString("Copied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image copy failed 的本地化字符串。
        /// </summary>
        internal static string t_CopyFailed {
            get {
                return ResourceManager.GetString("CopyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 does not exist! 的本地化字符串。
        /// </summary>
        internal static string t_ExistsNo {
            get {
                return ResourceManager.GetString("ExistsNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 existed. 的本地化字符串。
        /// </summary>
        internal static string t_ExistsYes {
            get {
                return ResourceManager.GetString("ExistsYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Explorer extension 的本地化字符串。
        /// </summary>
        internal static string t_ExplorerExt {
            get {
                return ResourceManager.GetString("ExplorerExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to add right-click menu item,  的本地化字符串。
        /// </summary>
        internal static string t_FailedAddMenu {
            get {
                return ResourceManager.GetString("FailedAddMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to delete right-click menu item,  的本地化字符串。
        /// </summary>
        internal static string t_FailedRemoveMenu {
            get {
                return ResourceManager.GetString("FailedRemoveMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not a valid file path. 的本地化字符串。
        /// </summary>
        internal static string t_NotValidPath {
            get {
                return ResourceManager.GetString("NotValidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unsupported image format. 的本地化字符串。
        /// </summary>
        internal static string t_OutMemory {
            get {
                return ResourceManager.GetString("OutMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 failed to delete! 的本地化字符串。
        /// </summary>
        internal static string t_RmFail {
            get {
                return ResourceManager.GetString("RmFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 successfully deleted. 的本地化字符串。
        /// </summary>
        internal static string t_RmOK {
            get {
                return ResourceManager.GetString("RmOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Seconds 的本地化字符串。
        /// </summary>
        internal static string t_Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Follow the system,Bright,Dark 的本地化字符串。
        /// </summary>
        internal static string t_Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please try running with administrator rights. 的本地化字符串。
        /// </summary>
        internal static string t_TryAdmin {
            get {
                return ResourceManager.GetString("TryAdmin", resourceCulture);
            }
        }
    }
}
